snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "kek"

[default]
input_parameters = "()"
return_type = "string"
file = "app.zip"
name = "orders_update_sp"
handler = "app.main"
execute_as_caller = true

[dev]
database = "KEK_DB"
schema = "HARMONIZED"
warehouse = "KEK_WH"
role = "KEK_ROLE"
overwrite = true
